insert into eiscremesorte(id, name, kategorie, kcal,  preis) values(eiscremesortedb_seq.nextVal, 'Bourbon Vanille', 'SAHNEEIS', 208, 3.65);
insert into eiscremesorte(id, name, kategorie, kcal,  preis) values(eiscremesortedb_seq.nextVal, 'Chocolate Chips', 'SAHNEEIS', 219, 3.65);
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (1, 'Milch');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (1, 'Kokosfett');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (1, 'Zucker');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (1, 'Schlagsahne');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (1, 'Bourbon-Vanilleextrakt');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (1, 'Vanilleschoten');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (2, 'Milch');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (2, 'Zucker');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (2, 'Kakao');
insert into eiscremesorte_zutaten (eiscremesorte_id, zutaten) values (2, 'Schlagsahne');